services:
  postgres:
    image: postgres:15
    container_name: event_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-net
    
  event-backend:
    container_name: event-backend
    build:
      context: ./event-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/event
      - APP_ENV=develop
    depends_on:
      - postgres
    command: sh start.sh
    networks:
      - event-net
      
  nextjs-app:
    container_name: event-frontend
    build:
      context: ./event-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    restart: always
    environment:
      - PORT=3001
      - API_URL=http://localhost:3000
    depends_on:
      - event-backend
    networks:
      - event-net
    volumes:
      - ./event-frontend:/app
    command: npm run dev
  

volumes:
    postgres_data: {}
  

networks:
  event-net:
    driver: bridge
